// <auto-generated />
namespace Excell_On_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addfktransHs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfktransHs));
        
        string IMigrationMetadata.Id
        {
            get { return "202204150451390_add-fk-transHs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
