// <auto-generated />
namespace Excell_On_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfulltable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfulltable));
        
        string IMigrationMetadata.Id
        {
            get { return "202204150438046_add-full-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
